### PR TITLE
fix: display correct positions for manual short 

### LINKED ISSUE #168: Swaps query might be causing positions issues
**Describe the bug**
- Folks who have manually minted + sold have reporting seeing incorrect short values 
- Someone who went long isn't able to see their position on the dashboard 

**To Reproduce**
1. Go short, manually rebalance (mint + sell more), close position 
2. Go long 

**Expected behavior**
Should show the accurate positions and positions should not disappear 

**Screenshots**
Screen Shot 2022-02-15 at 12 26 26 AM
Screen Shot 2022-02-15 at 12 27 58 AM
Screen Shot 2022-02-15 at 12 28 08 AM

### PR DESCRIPTION
**Pull request by yichiehliu**
# Task:

## Description

1. added vault history query, minted, open_short, burnt, close_short squeeth calculations
2. added toLowercase conversion & ?? condition check to make sure query variables are valid. Rn we sometimes send invalid query variables which will cause query result to be empty
3. moved first valid vault query to useVaultManager
4. added minted & manually sold short position calculations 
5. set the correct loading check for each value on position page
6. removed redundant query params

Fixes #168  (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Locally

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

### CODE REVIEW

**Review by alexisgauba — COMMENTED** [review]
Hmm looks like minted is goin in and out for me here 🤔 

https://user-images.githubusercontent.com/13340486/155933310-d65565e5-8b86-4221-91c4-2d60676aba47.mov

Also do you have a testing doc where you ran through scenarios?

**Review by KMKoushik — CHANGES_REQUESTED** [review]

**Comment by EstherSeyi** [comment]
I'm still having the issue where my swaps are not loading and so the UI doesn't show my position. I have a short position here
Screenshot 2022-03-02 at 22 04 47

File: packages/frontend/src/context/positions.tsx [hunk 1]
```diff
@@ -97,45 +99,32 @@ const PositionsProvider: React.FC = ({ children }) => {
...
   }, [depositedSqueeth.toString(), withdrawnSqueeth.toString()])
 
-  const { finalSqueeth, finalWeth } = useMemo(() => {
-    // dont include LPed & minted amount will be the correct short amount
-    const finalSqueeth = squeethAmount
-    const finalWeth = wethAmount.div(squeethAmount).multipliedBy(finalSqueeth)
-    return { finalSqueeth, finalWeth }
-  }, [squeethAmount.toString(), wethAmount.toString()])
+  //mintedSqueeth balance - mintedSold short position = existing mintedDebt in vault
+  //since LPed amount wont be deducted, will need to be deducted here
```
Comment (alexisgauba) [inline packages/frontend/src/context/positions.tsx:116]: looks like LP is not deducted in the below calc though? Is that intended? Maybe im just confused at the comment haha

Comment (yichiehliu) [reply packages/frontend/src/context/positions.tsx:116]: it is in line 118, which is mintedSqueeth.minus(mintedSoldShort).minus(depositedSqueeth).plus(withdrawnSqueeth) = minted squeeth, and I will update the comment to make it more clear lol

**Comment by yichiehliu** [comment]
> I'm still having the issue where my swaps are not loading and so the UI doesn't show my position. I have a short position here Screenshot 2022-03-02 at 22 04 47

I have removed the setVaultId in each trade component, and get vaultId from useVaultManger, it shld make the data fetching more smoothly

File: packages/frontend/src/context/positions.tsx (hunk 1 above)
Comment (alexisgauba) [reply packages/frontend/src/context/positions.tsx]: Ok gotcha, LP is deducted as part of which var in that equation?

Comment (yichiehliu) [reply packages/frontend/src/context/positions.tsx]: With .minus(depositedSqueeth).plus(withdrawnSqueeth) in line 118, depositedSqueeth.plus(withdrawnSqueeth) would be LPed amount

**Comment by EstherSeyi** [comment]
It works now!

Screenshot 2022-03-03 at 08 45 27

**Review by EstherSeyi — APPROVED** [review]

File: packages/frontend/pages/vault/[vid].tsx [hunk 2]
```diff
@@ -242,10 +242,10 @@ const SelectLP = React.memo<{ lpToken: number; setLpToken: (t: number) => void }
 
   const { data } = useQuery<positions, positionsVariables>(POSITIONS_QUERY, {
     variables: {
-      poolAddress: squeethPool?.toLowerCase(),
-      owner: address?.toLowerCase() || '',
+      poolAddress: squeethPool,
+      owner: address || '',
     },
-    fetchPolicy: 'no-cache',
+    fetchPolicy: 'cache-and-network',
```
Comment (KMKoushik) [inline packages/frontend/pages/vault/[vid].tsx:248]: LP positions were not showing because of this before. Did you test that flow? Apparently is some bug with the apollo client

**Review by KMKoushik — CHANGES_REQUESTED** [review]

File: packages/frontend/pages/vault/[vid].tsx (hunk 2 above)
Comment (yichiehliu) [reply packages/frontend/pages/vault/[vid].tsx:248]: ummm I tested on ropsten and it worked for me

Comment (yichiehliu) [reply packages/frontend/pages/vault/[vid].tsx:248]: But can change to cache-and-network for fetchPolicy

Comment (yichiehliu) [reply packages/frontend/pages/vault/[vid].tsx:248]: image
It showed up without refreshing

**Review by KMKoushik — APPROVED** [review]

File: packages/frontend/src/context/positions.tsx (hunk 1 above)
Comment (alexisgauba) [reply packages/frontend/src/context/positions.tsx]: ok maybe add a comment documenting that? i def wouldn't have known that so prob helpful for others 

what does depositedSqueeth represent and what does withdrawnSqueeth represent? Var names are a bit confusing imo

**Review by alexisgauba — APPROVED** [review]
Overall lgtm! 

Would improve var names / comments here for better understanding whenever we have to touch this code next https://github.com/opynfinance/squeeth-monorepo/pull/199#discussion_r819202700

File: packages/frontend/src/context/positions.tsx (hunk 1 above)
Comment (yichiehliu) [reply packages/frontend/src/context/positions.tsx]: Just added!

depositedSqueeth is accumulated deposited Squeeth in LP position and withdrawn Squeeth is acc. withdrawn squeeth in LP position, and accumulated deposited Squeeth - acc. withdrawn squeeth in LP position = LP debt
