### PR TITLE
Fe/direct selling swaps

### LINKED ISSUE #87: Update swaps query to pull from the shortHelper and Uniswap directly
**Describe the bug**
Right now the swaps query on the short side doesn't consider the Uniswap router, when it should because users manually mint and then sell on Uniswap, or manually buy back on Uniswap to burn 

**To Reproduce**
Manually mint and sell on Uniswap 

**Expected behavior**
Swaps router takes into account txns on Uniswap and properly classifies them as short if mint + sell directly on Uniswap

### PR DESCRIPTION
**Pull request by yichiehliu**
# Task:

## Description

1. add direct selling txs to txs history and make the sold balance correct if users manually sell oSQTH on uniswap(since currently manual selling is only supported on mainnet, would use original query method when users is not on the mainnet)

Fixes #87  (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update

## How Has This Been Tested

Please describe how to test to verify the changes. Provide instructions so we can reproduce.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] Added video recordings if it is a UI change

### CODE REVIEW

File: packages/frontend/src/hooks/useTransactionHistory.ts [hunk 1]
```diff
@@ -84,14 +86,14 @@ export const useTransactionHistory = () => {
...
-  const transactions = (data?.swaps || []).map((s: transactions_swaps) => {
+  const transactions = (swaps || []).map((s) => {
     const squeethAmount = new BigNumber(isWethToken0 ? s.amount1 : s.amount0)
     const ethAmount = new BigNumber(isWethToken0 ? s.amount0 : s.amount1)
     const time = new Date(Number(s.timestamp) * 1000).setUTCHours(0, 0, 0) / 1000
     const usdValue = ethAmount.multipliedBy(ethPriceMap[time]).abs()
 
     let transactionType = TransactionType.BUY
-    if (squeethAmount.isPositive() && s.recipient.toLowerCase() === swapRouter.toLowerCase()) {
+    if (squeethAmount.isPositive() && s.recipient.toLowerCase() !== shortHelper.toLowerCase()) {
```
Comment (alexisgauba) [inline packages/frontend/src/hooks/useTransactionHistory.ts:96]: hm not sure I understand this, we also want to include txns that go through shortHelper right? Or are we not tracking them here because we are tracking them elsewhere and this is just meant to be for swapRouter txns?

Comment (yichiehliu) [reply packages/frontend/src/hooks/useTransactionHistory.ts:96]: There are two conditions here, if s.recipient.toLowerCase() === shortHelper.toLowerCase(), that means users are doing OPEN_SHORT or CLOSE_SHORT, and if s.recipient.toLowerCase() !== shortHelper.toLowerCase(), that means users are doing BUY or SELL, but the pattern wont work for minted/burnt only txs, will figure out a way to distinguish them in the following pr.

Comment (alexisgauba) [reply packages/frontend/src/hooks/useTransactionHistory.ts:96]: Ok gotcha so this only affects the txn history, not the positions stuff, and it's just showing the distinction between open_short vs. minting vs. selling? 

And the next PR you're adding the separate actions?

Comment (yichiehliu) [reply packages/frontend/src/hooks/useTransactionHistory.ts:96]: Yh after this pr I will add separate actions, cuz it requires new vault history to distinguish minting from MINT_SHORT

**Review by alexisgauba — APPROVED** [review]
